---
title: "Results 2024"
author: "Michael Rustler"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Results 2025}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

# Men

## Men Starting Day 1

```{r men_all}
men <- teamstaffel::get_results("M", 
                                year = 2025,
                                event = "ST1")

DT::datatable(men,
              rownames = FALSE)

```

## Men BWB Only
```{r men_bwb_only}
is_bwb <- grepl(men$team, pattern = "Berliner\\s?Wasserbetriebe")
men_bwb <- men[is_bwb, ] 
men_bwb$place_bwb <- seq_len(nrow(men_bwb))
men_bwb <- dplyr::select(men_bwb, "place_bwb", dplyr::everything())
is_kwb <- stringr::str_extract(men_bwb$team, pattern = "[0-9][0-9]?[0-9]?") %in% c(99:101,103)
men_bwb[["place_kwb"]][is_kwb] <- seq_len(sum(is_kwb))
men_bwb <- dplyr::select(men_bwb, "place_kwb", dplyr::everything()) 

DT::datatable(men_bwb,
              options = list(pageLength = 100),
              rownames = FALSE)

```


### Statistics

```{r men_bwb_only_stats}
is_kwb <- stringr::str_starts(men$team, pattern = "Berliner.*Wasser") & stringr::str_extract(men$team, pattern = "[0-9][0-9]?[0-9]?") %in% c(99:101,103)
men[["place_kwb"]][is_kwb] <- seq_len(sum(is_kwb))
men[["kwb_team"]][is_kwb] <- sprintf("KWB%d", seq_len(sum(is_kwb)))

men$time_minutes <- as.numeric(lubridate::seconds(lubridate::hms(men$finish_time))/60)

ecdf_function <- ecdf(men$time_minutes)

men_is_kwb <- men[is_kwb,]
men_is_kwb$percentile <- ecdf_function(men_is_kwb$time_minutes)*100

density_minutes <- density(men$time_minutes)


plot(density_minutes, 
     xlab = "Time (minutes)",
     main = "")
abline(v = men_is_kwb$time_minutes,  col = "blue")
text(x = men_is_kwb$time_minutes*0.99,
     labels = sprintf("%s (%03.1f %%)", men_is_kwb$kwb_team, men_is_kwb$percentile),
     y = 0.75* max(density_minutes$y),
     srt = 90,
     col = "blue")
     

plot(x = men$time_minutes, 
     y = men$place,
     xlab = "Time (minutes)",
     ylab = "Place",
     main = "", 
     type = "l",
     las = 1)
abline(v = men_is_kwb$time_minutes,  col = "blue")
text(x = men_is_kwb$time_minutes*0.99,
     labels = sprintf("%s (%03.1f %%)", men_is_kwb$kwb_team, men_is_kwb$percentile),
     y = median(men_is_kwb$place),
     srt = 90,
     col = "blue")
     
```



# Women Starting Day 1

```{r women}
women <- teamstaffel::get_results("W", year = 2025, event = "ST1")
DT::datatable(women)

```


## Women BWB Only
```{r women_bwb_only}
is_bwb <- grepl(women$team, pattern = "Berliner\\s?Wasserbetriebe")
women_bwb <- women[is_bwb, ] 
women_bwb$place_bwb <- seq_len(nrow(women_bwb))
women_bwb <- dplyr::select(women_bwb, "place_bwb", dplyr::everything())

DT::datatable(women_bwb,
              options = list(pageLength = 100),
              rownames = FALSE)

```
